version: "2.1"
services:
  mysql:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  server:
    build: .
    depends_on:
      - mysql
      - consul
    environment:
      DB_HOST: mysql
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
  consul:
    image: consul:1.12
    restart: always
    ports:
      - "8500:8500"
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client='0.0.0.0'"
  rabbit:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"